replicaCount: 2

image:
  repository: CHANGEME_ECR_REPOSITORY   # e.g., <aws_account_id>.dkr.ecr.<region>.amazonaws.com/sample-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/health"
  prometheus.io/port: "8080"

nodeSelector: {}
tolerations: []
affinity: {}
